set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER gcc)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TC_SYSROOT $ENV{TC_SYSROOT})
set(TC_INSTALL_DIR $ENV{TC_INSTALL_DIR})
set(TC_THIRDPARTY $ENV{TC_THIRDPARTY})
