#!/bin/bash

set -e

TC_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
TC_ROOT_DIR=$TC_SCRIPT_DIR/../../../..
TC_SOURCE_REPO=$TC_ROOT_DIR/src

TC_HOST_COMPILER_TUPLE=x86_64-linux-gnu
TC_COMPILER_TUPLE=x86_64-unknown-linux-gnu
TC_COMPILER_DIR=$TC_SCRIPT_DIR/$TC_COMPILER_TUPLE
TC_COMPILER_BINDIR=$TC_COMPILER_DIR/bin
TC_COMPILER_CC=$TC_COMPILER_BINDIR/$TC_COMPILER_TUPLE-gcc
TC_COMPILER_CXX=$TC_COMPILER_BINDIR/$TC_COMPILER_TUPLE-g++

TC_CROSS_COMPILE=1
TC_SYSROOT=$TC_COMPILER_DIR/$TC_COMPILER_TUPLE/sysroot
TC_INSTALL_DIR=$TC_SYSROOT/usr
TC_THIRDPARTY=$TC_SCRIPT_DIR/thirdparty

TC_CMAKE_TOOLCHAIN=$TC_SCRIPT_DIR/toolchain.cmake
TC_MESON_CROSSFILE=$TC_SCRIPT_DIR/meson-crossfile.ini

export PATH="$PATH:$TC_COMPILER_BINDIR"
export CC=$TC_COMPILER_CC
export CXX=$TC_COMPILER_CXX
export PKG_CONFIG_PATH="$TC_INSTALL_DIR/share/pkgconfig:$TC_INSTALL_DIR/lib/pkgconfig"
export TC_SYSROOT=$TC_SYSROOT
export TC_COMPILER_CC=$TC_COMPILER_CC
export TC_COMPILER_CXX=$TC_COMPILER_CXX
