set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_C_COMPILER cl)
set(CMAKE_CXX_COMPILER cl)

set(TC_SYSROOT $ENV{TC_SYSROOT})
set(TC_INSTALL_DIR $ENV{TC_INSTALL_DIR})
set(TC_THIRDPARTY $ENV{TC_THIRDPARTY})
