set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR amd64)

set(CMAKE_SYSROOT $ENV{TC_SYSROOT})

set(CMAKE_C_COMPILER $ENV{TC_COMPILER_CC})
set(CMAKE_CXX_COMPILER $ENV{TC_COMPILER_CXX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TC_THIRDPARTY_DIR ${CMAKE_CURRENT_LIST_DIR}/thirdparty)
set(TC_INSTALL_DIR $ENV{TC_SYSROOT})
